arch:
    - amd64
    - ppc64le
sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
matrix:
  allow_failures: []
  fast_finish: true
#Excluding below versions since they are not supported by ppc64le    
jobs: 
  exclude:
    - node_js: "0.10"
      arch: ppc64le
    - node_js: "0.12"
      arch: ppc64le
